version: "3.7"
services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - 5678:5678
    environment:
      N8N_BASIC_AUTH_ACTIVE: ${N8N_AUTH_ACTIVE:-false}
      N8N_BASIC_AUTH_USER: ${N8N_USERNAME}
      N8N_BASIC_AUTH_PASSWORD: ${N8N_PASSWORD}
    volumes:
      - data-shared:/shared
      - n8n-volume:/root/.n8n
      - ./config/n8n-start.sh:/docker-entrypoint.sh
    user: root
    # command: /bin/sh -c "node n8n"
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    depends_on:
      - webapp
      - n8n
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - data-shared:/shared
      - frontend-app-files:/app
  webapp:
    build:
      context: ..
    image: c2dhunilu/covid-19-survey-lux:latest
    volumes:
      - frontend-app-files:/app
    command: >
      /bin/sh -c "rm -rf /app/* &&
                  echo 'Files in /app :' && 
                  ls -lat /app/ &&
                  cp -r /covid-19-survey-lux/* /app/ &&
                  echo 'Files in /app :' &&
                  ls -lat /app/"
volumes:
  data-shared:
  frontend-app-files:
  n8n-volume:
